### ISSUE TITLE
Closing llnk tag

### ISSUE THREAD

**Issue by volyx** [jonkemp/useref#11]
Now useref doesn't close link tag. See refManager.js:23. When I'm processing html template with thymeleaf template engine it fails.

Useref generates not compatible xml template.

`org.xml.sax.SAXParseException; lineNumber: 9; columnNumber: 3; The element type "link" must be terminated by the matching end-tag "</link>".
    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
    at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
    at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanEndElement(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)`

**Comment by jonkemp** [comment]
This can actually be done with custom blocks if you are wanting that. See here: https://github.com/jonkemp/useref/pull/13#issuecomment-243551499.
